prep-work/prep-course/w4/blogger/config/routes.rb
Blogger::Application.routes.draw do

  root to: 'articles#index'

  resources :articles do
    resources :comments do
      member do
        post :upvote
        post :downvote
      end
    end
    member do
      post :upvote
      post :downvote
    end
  end

  resources :tags, only: [:index, :show]

  resources :authors

  resources :author_sessions, only: [ :new, :create, :destroy ]
  get 'login'  => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'

end

prep-work/prep-course/w4/blogger/app/models/article.rb
class Article < ActiveRecord::Base

  acts_as_taggable

  has_many :comments
  belongs_to :author

  default_scope -> { order(created_at: :desc) }

  has_attached_file :image
  validates_attachment_content_type :image, :content_type => [
                                                               "image/jpg",
                                                               "image/jpeg",
                                                               "image/png"
                                                              ]

  def root_comments
    self.comments.select { |comment| comment.parent.nil? }
  end

end

prep-work/prep-course/w4/blogger/app/models/author.rb
class Author < ActiveRecord::Base

  has_many :articles
  has_many :comments

  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password

end

prep-work/prep-course/w4/blogger/app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :article
  belongs_to :author
  belongs_to :parent, class_name: "Comment"
  has_many :children, class_name: "Comment", foreign_key: "parent_id"

end

prep-work/prep-course/w4/blogger/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

prep-work/prep-course/w4/blogger/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  include ArticlesHelper

  before_filter :require_login, except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comment.article_id = @article.id
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.author_id = current_user.id
    @article.save

    flash.notice = "Article '#{@article.title}' Created!"

    redirect_to article_path(@article)
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)

    flash.notice = "Article '#{@article.title}' Updated!"

    redirect_to article_path(@article)
  end

  def destroy
    article = Article.find(params[:id])
    title = article.title
    article.destroy

    flash.notice = "Article '#{title}' Deleted!"

    redirect_to articles_path
  end

  def upvote
    @article = Article.find_by_id(params[:id])
    @article.update_attributes(upvotes: @article.upvotes + 1)

    flash.notice = "Article Upvoted!"

    redirect_to article_path
  end

  def downvote
    @article = Article.find_by_id(params[:id])
    @article.update_attributes(downvotes: @article.downvotes + 1)
    redirect_to article_path(@article)
  end

end

prep-work/prep-course/w4/blogger/app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController

  def new
  end

  def create
    if login(params[:email], params[:password])
      redirect_back_or_to(articles_path, notice: 'Logged in successfully.')
    else
      flash.now.alert = "Login failed."
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to(:authors, notice: 'Logged out!')
  end

end

prep-work/prep-course/w4/blogger/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_filter :require_login, except: [:new, :create]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render action: 'show', status: :created, location: @author }
      else
        format.html { render action: 'new' }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end

end

prep-work/prep-course/w4/blogger/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  include CommentsHelper

  before_filter :require_login, except: [:create]

  def create
    @comment = Comment.new(comment_params)
    if params[:parent_id]
      @comment.parent_id = params[:parent_id].to_i
    end
    @comment.article_id = params[:article_id]
    @comment.author_id = current_user.id

    @comment.save

    flash.notice = "Comment Created!"

    redirect_to article_path(@comment.article)
  end

  def upvote
    @comment = Comment.find_by_id(params[:id])
    @comment.update_attributes(upvotes: @comment.upvotes + 1)
    redirect_to article_path(@comment.article)
  end

  def downvote
    @comment = Comment.find_by_id(params[:id])
    @comment.update_attributes(downvotes: @comment.downvotes + 1)
    redirect_to article_path(@comment.article)
  end

end

prep-work/prep-course/w4/blogger/app/controllers/tags_controller.rb
class TagsController < ApplicationController

  before_filter :require_login, only: [:destroy]

  def index
    @tags = ActsAsTaggableOn::Tag.all
  end

  def show
    @tag =  ActsAsTaggableOn::Tag.find(params[:id])
    @articles = Article.tagged_with(@tag.name)
  end

end

prep-work/prep-course/w4/blogger/app/helpers/application_helper.rb
module ApplicationHelper
end

prep-work/prep-course/w4/blogger/app/helpers/articles_helper.rb
module ArticlesHelper

  def article_params
    params.require(:article).permit(:title, :body, :tag_list, :image)
  end

end

prep-work/prep-course/w4/blogger/app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

prep-work/prep-course/w4/blogger/app/helpers/authors_helper.rb
module AuthorsHelper
end

prep-work/prep-course/w4/blogger/app/helpers/comments_helper.rb
module CommentsHelper

  def comment_params
    params.require(:comment).permit(:body)
  end

end

prep-work/prep-course/w4/blogger/app/helpers/tags_helper.rb
module TagsHelper
end

prep-work/prep-course/w4/blogger/app/views/articles/_article.html.erb
<li class="article">
  <div class="media">
    <%= render partial: 'shared/vote_buttons',
        locals: { this_comment_id: nil, this_article_id: article.id,
                  upvotes: article.upvotes } %>
    <div class="media-body article-preview">
      <h4 class="media-heading">
        <%= link_to article.title, article_path(article),
            class: 'article_title', id: "article_#{article.id}" %>
      </h4>
      <div><%= "submitted #{time_ago_in_words(article.created_at)} ago" %></div>
      <div>Tags: <%= render article.tags %></div>
    </div>
  </div>
</li>

prep-work/prep-course/w4/blogger/app/views/articles/_comment.html.erb
<div class="media">
  <%= render partial: 'shared/vote_buttons',
      locals: { this_comment_id: comment.id, this_article_id: nil,
                upvotes: comment.upvotes } %>
  <div class="media-body">
    <h4>
      <a type="button" class="btn btn-xs btn-default"
       id="comment_button_<%= comment.id %>"
       onClick="handleCollapse(<%= comment.id %>)">-</a>
      <span>Comment by <%= comment.author.username %></span>
    </h4>

    <div class= "comment_block" id="comment_block_<%= comment.id %>">
      <p>submitted <%= time_ago_in_words(comment.created_at) %> ago</p>

      <p class="comment_body"><%= comment.body %></p>

      <%= render partial: 'comments/reply_form',
            locals: { parent_id: comment.id } %>

      <% if comment.children.any? %>
        <%= render partial: 'articles/comment', collection: comment.children %>
      <% end %>
    </div>
  </div>
</div>

prep-work/prep-course/w4/blogger/app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list %>
  </p>
  <p>
    <% if @article.image.exists? %>
        <%= image_tag @article.image.url %><br/>
    <% end %>
    <%= f.label :image, "Attach a New Image" %><br />
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

prep-work/prep-course/w4/blogger/app/views/articles/edit.html.erb
<h1>Edit an Article</h1>

<%= render partial: 'form' %>

prep-work/prep-course/w4/blogger/app/views/articles/index.html.erb
<ul class="articles">
  <div><%= render @articles %></div>
</ul>

<% if logged_in? %>
  <%= link_to "Create a New Article", new_article_path, class: "new_article" %>
<% end %>

prep-work/prep-course/w4/blogger/app/views/articles/new.html.erb
<h1>Create a New Article</h1>

<%= render partial: 'form' %>

prep-work/prep-course/w4/blogger/app/views/articles/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h2 class="panel-title">
      <%= link_to "#{@article.title}", article_path(@article) %>
    </h2>
    <div class="panel-sub">
      <div><%= "submitted #{time_ago_in_words(@article.created_at)} ago" %></div>
      <div>Tags: <%= render @article.tags %></div>
    </div>
  </div>
  <div class="panel-body">
    <% if @article.image.exists? %>
      <p><%= image_tag @article.image.url %></p>
    <% end %>
    <p><%= @article.body %></p>
  </div>
</div>

<%= render partial: 'comments/form' %>

<h3>Comments (<%= @article.comments.length %>)</h3>

<ul class="media-list">
  <%= render partial: 'articles/comment', collection: @article.root_comments %>
</ul>

prep-work/prep-course/w4/blogger/app/views/author_sessions/new.html.erb
<h1>Login</h1>

<%= form_tag author_sessions_path, method: :post do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email %>
    <br/>
  </div>
  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
    <br/>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

<%= link_to 'Back', articles_path %>

prep-work/prep-course/w4/blogger/app/views/comments/_form.html.erb
<h5>Post a Comment</h5>

<%= form_for [@article, @comment] do |f| %>
  <p>
    <%= f.text_area :body, rows: 5, cols: 100 %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>

<% end %>

prep-work/prep-course/w4/blogger/app/views/comments/_reply_form.html.erb
<a data-toggle="collapse" href="#comment_<%= parent_id %>">
  Reply
</a>
<div class= "collapse" id="comment_<%= parent_id %>">
  <%= form_for [ @article, @comment ] do |f| %>
    <div><%= hidden_field_tag :parent_id, parent_id %></div>
    <p>
      <%= f.text_area :body, rows: 5, cols: 100 %>
    </p>
    <p>
      <%= f.submit 'Submit' %>
    </p>
  <% end %>
</div>

prep-work/prep-course/w4/blogger/app/views/tags/index.html.erb
<h1>Tags</h1>
<%= render @tags %>

prep-work/prep-course/w4/blogger/app/views/tags/show.html.erb
<h1>Articles tagged with '<%= @tag.name %>'</h1>
<div><%= render @articles %></div>